version: 2
updates:
  - package-ecosystem: github-actions
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directories:
      - /
      - /backend
      - /client
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directories:
      - /
      - /backend/cloud
      - /client/cloud
    schedule:
      interval: weekly
